### ISSUE TITLE
Want to ask you some questions

### ISSUE THREAD

**Issue by wy-luke** [JONGGON/DeepHumanPrediction#1]
Firstly I want to say thank you for your repo, it is very useful for me.
I am an university student and I would graduate next month. In my Graduation Project, your code is very useful.
But I have some questions 
(I have create a conda env with your python version,in Manjaro Linux system)

1. how to run your code, just run the main.py?
2.when I run the main.py in Motion_Prediction_Simple, I get this error

```
Motion_Data_Preprocessing_Imported
MotionNet_imported
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/run/media/luke/Data/BBBishe/BS/DeepHumanPrediction/DeepHumanPrediction/Code/DeepHumanPrediction/Motion_Prediction_Simple/main.py", line 5, in <module>
    MotionNet(epoch=1000, batch_size=10, save_period=1000, optimizer='sgd', learning_rate=0.001, use_cudnn=True)
  File "/run/media/luke/Data/BBBishe/BS/DeepHumanPrediction/DeepHumanPrediction/Code/DeepHumanPrediction/Motion_Prediction_Simple/network.py", line 18, in MotionNet
    motion_data, class_number, time_step, xyz_rotation =  br.Motion_Data_Preprocessing()
  File "/run/media/luke/Data/BBBishe/BS/DeepHumanPrediction/DeepHumanPrediction/Code/DeepHumanPrediction/Motion_Prediction_Simple/bvh_reader.py", line 50, in Motion_Data_Preprocessing
    xyz_rotation=len(Data[0][0])
IndexError: list index out of range
```
3.when I run main.py in Motion_Prediction_encoding_decoding folder, I get this
```
Motion_Data_Preprocessing_Imported
Motion_Data_Making_Imported
<<<Motion with encoding decoding>>>
[]
```
after this, it will stop.

I am very very grateful if you could help me. Thank you very much!!!

**Comment by JONGGON** [comment]
I have to run it myself, it's 3 years ago, so ...
I think you can just run it..

I'll try it once and contact you

**Comment by wy-luke** [comment]
@JONGGON  Thank you so much!!!! 
Best wishes to you!

**Comment by JONGGON** [comment]
When I try it myself, it works.
My operating system is ubuntu16.04, window10
is.

**Comment by JONGGON** [comment]
You can check the location of the data.
I think it's reading the location of the data incorrectly.

**Comment by JONGGON** [comment]
>@wy-luke

When I try it myself, it works.
My operating system is ubuntu16.04, window10
is.

You can check the location of the data.
I think it's reading the location of the data incorrectly.

**Comment by wy-luke** [comment]
@JONGGON 
I'm sorry for not replying you.
I have a test tomorrow, I have been preparing it these days.
When I change the data path, the error solved. But anothe error appear.
I thought it was mxnet. I use mxnet-0.12.1, and cudatoolkit8.0 as you said.
which version do you use?
Thanks for helping me. 😊

**Comment by JONGGON** [comment]
😀 i use  mxnet 1.6.0 and cuda 10.1.168, cudnn 7.5.0
Thank you!!!
​
 tip)
You can install cuda, cudnn on the conda channel!!
​
-----Original Message-----

**Comment by wy-luke** [comment]
OK, I'll try it.
Thanks very very much




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jonggon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月18日(星期一) 中午11:05
收件人:&nbsp;"JONGGON/DeepHumanPrediction"<DeepHumanPrediction@noreply.github.com&gt;;
抄送:&nbsp;"wykj.luke"<li1078797083@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [JONGGON/DeepHumanPrediction] Want to ask you some questions (#1)





 😀 i use  mxnet 1.6.0 and cuda 10.1.168, cudnn 7.5.0
 Thank you!!!
 ​
  tip)
 You can install cuda, cudnn on the conda channel!!
 ​
 -----Original Message-----

**Comment by wy-luke** [comment]
@JONGGON Yes, it works!
mxnet 1.6.0 and cuda 10.1.168, cudnn 7.5.0, python3.6.1
Thank you so much!!! You are such a nice guy. Give you my all best wishes!!!!

**Comment by JONGGON** [comment]
@wy-luke
oh, I'm glad to hear that!!!!
if you have any other problems, please contact me again!!!  
thank you.

**Comment by wy-luke** [comment]
Do you still have you paper? And could I have a look?
I search it on the Internet, but didn't find it.
If it is confidential, just ignore my request.


Thanks a lot for helping me.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jonggon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月21日(星期四) 中午12:51
收件人:&nbsp;"JONGGON/DeepHumanPrediction"<DeepHumanPrediction@noreply.github.com&gt;;
抄送:&nbsp;"wykj.luke"<li1078797083@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [JONGGON/DeepHumanPrediction] Want to ask you some questions (#1)





 
@wy-luke
 oh, I'm glad to hear that!!!!
 if you have any other problems, please contact me again!!!
 thank you.

**Comment by JONGGON** [comment]
@wy-luke 

yes. I have it, but the paper is written by korean languages...
i have also ppt slides... but The details are not written(this is also written by korean languages..)
 Do you need this?

**Comment by wy-luke** [comment]
yes, I want it. I can translate it.
You can sent it to my gmail.


wykj.luke@gmail.com


Thanks!!!!!!!!!!!
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jonggon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月22日(星期五) 上午10:26
收件人:&nbsp;"JONGGON/DeepHumanPrediction"<DeepHumanPrediction@noreply.github.com&gt;;
抄送:&nbsp;"wykj.luke"<li1078797083@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [JONGGON/DeepHumanPrediction] Want to ask you some questions (#1)





 
@wy-luke
 
yes. I have it, but the paper is written by korean languages...
 i have also ppt slides... but The details are not written(this is also written by korean languages..)
 Do you need this?

**Comment by JONGGON** [comment]
@wy-luke 

okay, I'm working now,
I'll send you paper & ppt after work .
thank you !!
